language: node_js
node_js:
  - "6"
after_success:
  - echo $TRAVIS_BARNCH
  - echo $TRAVIS_EVENT_TYPE
  - 'if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_EVENT_TYPE" = "push"]]
    then
      node generate_change.js
    fi'